import type { BattleState } from "./types";

export const MOCK_BATTLE: BattleState = {
  phase: "complete",
  featureRequest:
    "Add rate limiting middleware that caps API requests at 100/min per IP, returns 429 with Retry-After header, and stores counters in-memory.",
  distinctions: [
    {
      label: "Fastest Runtime",
      contenderId: "sprinter",
      evidence: "p95 latency 3.1 ms vs 4.2 ms (Architect) and 6.8 ms (Minimalist)",
    },
    {
      label: "Smallest Diff",
      contenderId: "minimalist",
      evidence: "34 lines changed across 2 files — 61% fewer lines than Sprinter",
    },
    {
      label: "Lowest Complexity",
      contenderId: "architect",
      evidence:
        "Cyclomatic complexity 4 — single responsibility per module, clear separation of concerns",
    },
  ],
  contenders: [
    {
      id: "minimalist",
      label: "Minimalist",
      tagline: "Smallest correct diff",
      status: "eliminated",
      finalAction: "Eliminated — 2 acceptance tests failed",
      testsPassed: 18,
      testsTotal: 20,
      filesChanged: 2,
      linesChanged: 34,
      agentTimeMs: 4210,
      eliminationReason: "Acceptance tests failed: Retry-After header missing (2/20 failed)",
      gauntlet: {
        build:               "pass",
        "existing-tests":    "pass",
        "acceptance-tests":  "fail",
        "typescript-strict": "pass",
        "no-new-deps":       "pass",
        "api-compatibility": "pass",
      },
      benchmarks: [
        { label: "p50 latency", value: "3.4 ms",   raw: 3.4,  lowerIsBetter: true },
        { label: "p95 latency", value: "6.8 ms",   raw: 6.8,  lowerIsBetter: true },
        { label: "p99 latency", value: "11.2 ms",  raw: 11.2, lowerIsBetter: true },
        { label: "throughput",  value: "9,200 rps", raw: 9200, lowerIsBetter: false },
      ],
      testResults: [
        { name: "rate limit: blocks at 101st request",   passed: true,  durationMs: 12 },
        { name: "rate limit: returns 429 status",        passed: true,  durationMs: 8  },
        { name: "rate limit: Retry-After header present",passed: false, durationMs: 9  },
        { name: "rate limit: counter resets after window",passed: true,  durationMs: 14 },
        { name: "rate limit: per-IP isolation",          passed: false, durationMs: 11 },
        { name: "existing: auth middleware untouched",   passed: true,  durationMs: 6  },
      ],
    },
    {
      id: "sprinter",
      label: "Sprinter",
      tagline: "Optimized for runtime performance",
      status: "survived",
      finalAction: "All 20 acceptance tests passed · Gauntlet cleared",
      testsPassed: 20,
      testsTotal: 20,
      filesChanged: 3,
      linesChanged: 89,
      agentTimeMs: 5870,
      eliminationReason: null,
      gauntlet: {
        build:               "pass",
        "existing-tests":    "pass",
        "acceptance-tests":  "pass",
        "typescript-strict": "pass",
        "no-new-deps":       "pass",
        "api-compatibility": "pass",
      },
      benchmarks: [
        { label: "p50 latency", value: "1.8 ms",    raw: 1.8,   lowerIsBetter: true },
        { label: "p95 latency", value: "3.1 ms",    raw: 3.1,   lowerIsBetter: true },
        { label: "p99 latency", value: "5.4 ms",    raw: 5.4,   lowerIsBetter: true },
        { label: "throughput",  value: "14,100 rps", raw: 14100, lowerIsBetter: false },
      ],
      testResults: [
        { name: "rate limit: blocks at 101st request",    passed: true, durationMs: 4 },
        { name: "rate limit: returns 429 status",         passed: true, durationMs: 3 },
        { name: "rate limit: Retry-After header present", passed: true, durationMs: 4 },
        { name: "rate limit: counter resets after window",passed: true, durationMs: 5 },
        { name: "rate limit: per-IP isolation",           passed: true, durationMs: 4 },
        { name: "existing: auth middleware untouched",    passed: true, durationMs: 3 },
      ],
    },
    {
      id: "architect",
      label: "Architect",
      tagline: "Maintainability & clean structure",
      status: "survived",
      finalAction: "All 20 acceptance tests passed · Gauntlet cleared",
      testsPassed: 20,
      testsTotal: 20,
      filesChanged: 6,
      linesChanged: 187,
      agentTimeMs: 9340,
      eliminationReason: null,
      gauntlet: {
        build:               "pass",
        "existing-tests":    "pass",
        "acceptance-tests":  "pass",
        "typescript-strict": "pass",
        "no-new-deps":       "pass",
        "api-compatibility": "pass",
      },
      benchmarks: [
        { label: "p50 latency", value: "2.1 ms",    raw: 2.1,   lowerIsBetter: true },
        { label: "p95 latency", value: "4.2 ms",    raw: 4.2,   lowerIsBetter: true },
        { label: "p99 latency", value: "7.1 ms",    raw: 7.1,   lowerIsBetter: true },
        { label: "throughput",  value: "12,400 rps", raw: 12400, lowerIsBetter: false },
      ],
      testResults: [
        { name: "rate limit: blocks at 101st request",    passed: true, durationMs: 9  },
        { name: "rate limit: returns 429 status",         passed: true, durationMs: 7  },
        { name: "rate limit: Retry-After header present", passed: true, durationMs: 8  },
        { name: "rate limit: counter resets after window",passed: true, durationMs: 11 },
        { name: "rate limit: per-IP isolation",           passed: true, durationMs: 9  },
        { name: "existing: auth middleware untouched",    passed: true, durationMs: 6  },
      ],
    },
  ],
};
